<a href="https://colab.research.google.com/github/SungchulLee/colab/blob/main/exercise_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###***Chapter 0 Installment Extra Packages***

#####***Install Some Packages***

In [2]:
!pip install pandas-datareader
!pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


#####***Import Basic Modules***

In [3]:
import matplotlib.pyplot as plt
import numpy as np; np.random.seed(0)
import pandas as pd
import yfinance as yf
from scipy import stats

###***Chapter 2 Numpy Array***

In [ ]:
def main():
    np.random.seed(1010)
    love_scores = np.round( np.random.uniform(low=0, high=100, size=(10,)), 2 )
    print(love_scores,end="\n\n")

    love_scores_matrix = np.abs( love_scores.reshape( (1,-1) ) - love_scores.reshape( (-1,1) ) )
    print(love_scores_matrix)

if __name__ == "__main__":
    main()

[39.43 17.56  7.27 19.19 39.98 41.81 76.26 52.14 41.09 53.74]

[[ 0.   21.87 32.16 20.24  0.55  2.38 36.83 12.71  1.66 14.31]
 [21.87  0.   10.29  1.63 22.42 24.25 58.7  34.58 23.53 36.18]
 [32.16 10.29  0.   11.92 32.71 34.54 68.99 44.87 33.82 46.47]
 [20.24  1.63 11.92  0.   20.79 22.62 57.07 32.95 21.9  34.55]
 [ 0.55 22.42 32.71 20.79  0.    1.83 36.28 12.16  1.11 13.76]
 [ 2.38 24.25 34.54 22.62  1.83  0.   34.45 10.33  0.72 11.93]
 [36.83 58.7  68.99 57.07 36.28 34.45  0.   24.12 35.17 22.52]
 [12.71 34.58 44.87 32.95 12.16 10.33 24.12  0.   11.05  1.6 ]
 [ 1.66 23.53 33.82 21.9   1.11  0.72 35.17 11.05  0.   12.65]
 [14.31 36.18 46.47 34.55 13.76 11.93 22.52  1.6  12.65  0.  ]]


####***Section 2 How to Make Numpy Array***

#####***Exercise***

Create your own 4D array.

######***Solution***

In [ ]:
def main ():
    arr_1 = np.array([1,2,3])             # shape (3,)
    arr_2 = np.array([arr_1,arr_1,arr_1]) # shape (3, 3)
    arr_3 = np.array([arr_2,arr_2,arr_2]) # shape (3, 3, 3)
    arr_4 = np.array([arr_3,arr_3,arr_3]) # shape (3, 3, 3, 3)

    a = arr_4
    print(f'{a = }',f'{type(a) = }',f'{a.ndim = }',f'{a.shape = }',sep="\n")

if __name__ == "__main__":
    main()

a = array([[[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]]])
type(a) = <class 'numpy.ndarray'>
a.ndim = 4
a.shape = (3, 3, 3, 3)


###***Chapter 3 Random Numpy Array***

####***Section 3 Uniform Distribution***

#####***Coin Flip using np.random.uniform***

Flip fair coin 10 time using `np.random.uniform` and print "H" for head coins and "T" for tail coins.

######***Solution***

In [6]:
def main():
    n = 10
    p = 0.5

    for i in range(n):
        if np.random.uniform() > 1 - p: 
            print("H", end=' ')
        else:
            print("T", end=' ')

if __name__ == "__main__":
    main()

H H T H T H T H H T 

In [9]:
def main():
    n = 10
    p = 0.5

    coin = []
    for i in range(n):
        if np.random.uniform() > 1 - p: 
            coin.append("H")
        else:
            coin.append("T")
    print(coin)

if __name__ == "__main__":
    main()

['H', 'T', 'H', 'T', 'T', 'T', 'H', 'T', 'T', 'T']


In [8]:
def main():
    n = 10
    p = 0.5
    coin = ["H" if (np.random.uniform() > 1 - p) else "T" for i in range(n)]
    print(coin)

if __name__ == "__main__":
    main()

['T', 'T', 'H', 'T', 'H', 'H', 'T', 'T', 'T', 'T']


#####***Vecorization - Coin Flip using np.random.uniform***

Flip fair coin 10 time using `np.random.uniform` and print 1 for head coins and 0 for tail coins.

######***Solution***

In [ ]:
def main():
    n = 10
    p = 0.5
    uniform_sample = np.random.uniform(size=(n,))
    coin = np.zeros_like(uniform_sample)
    coin[uniform_sample > 1-p] = 1.
    print(coin)

if __name__ == "__main__":
    main()

[0. 0. 1. 0. 0. 0. 1. 0. 1. 0.]


####***Section 4 Distributions related to Coin Flip***

#####***Coin Flip using np.random.binomial***

Flip fair coin 10 time using `np.random.binomial` and print "H" for head coins and "T" for tail coins.

######***Solution***

In [7]:
def main():
    n = 10
    p = 0.5

    for i in range(n):
        if np.random.binomial(1, p) == 1: 
            print("H", end=' ')
        else:
            print("T", end=' ')

if __name__ == "__main__":
    main()

T H T H T H H H H H 

###***Chapter 5 Numpy Array Methods and Functions***

####***Section 2 Statistics Methods***

#####***High School Reunion Problem [eng](https://www.youtube.com/watch?v=GFOxU1QESrI&list=PL9oKUrtC4VP6gDp1Vq3BzfViO0TWgR0vR&index=10)***

With your high school reunion fast approaching, you decide to get in shape and lose some weight . You record your weight every day for five weeks starting on a Monday.
```
dailywts = 185 - np.arange(5*7)/5

# print(dailywts)
# [185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
#  182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
#  180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]
```

######***Solution***

In [ ]:
def main():
    dailywts = 185 - np.arange(5*7)/5 
    x = np.mean( dailywts.reshape( (5, -1) )[:,-2:], axis=1 )
    print(x)

if __name__ == "__main__":
    main()

[183.9 182.5 181.1 179.7 178.3]


####***Section 5 Functions***

#####***Professor Prick [eng](https://www.youtube.com/watch?v=U7pkujDW6gU&list=PL9oKUrtC4VP6gDp1Vq3BzfViO0TWgR0vR&index=20)***

In [ ]:
def main():
    np.random.seed(80085)
    scores = np.round(np.random.uniform(low=30, high=100, size=15))
    print(scores)

    count = 0
    for i, item in enumerate(scores):
        if item < 60.:
            scores[i] = 0.
            count += 1
            if count >= 3:
                break
    print(scores)
        
if __name__ == "__main__":
    main()

[55. 32. 84. 96. 41. 46. 96. 94. 48. 91. 41. 31. 99. 41. 97.]
[ 0.  0. 84. 96.  0. 46. 96. 94. 48. 91. 41. 31. 99. 41. 97.]


In [ ]:
def main():
    np.random.seed(80085)
    scores = np.round(np.random.uniform(low=30, high=100, size=15))
    print(scores)

    scores[np.nonzero(scores < 60.)[0][:3]] = 0.
    print(scores)
        
if __name__ == "__main__":
    main()

[55. 32. 84. 96. 41. 46. 96. 94. 48. 91. 41. 31. 99. 41. 97.]
[ 0.  0. 84. 96.  0. 46. 96. 94. 48. 91. 41. 31. 99. 41. 97.]


###***Chapter 6 Indexing and Slicing***

####***Section 1 Indexing***

#####***Gold Miner [eng](https://www.youtube.com/watch?v=Xqy8tF2sIko&list=PL9oKUrtC4VP6gDp1Vq3BzfViO0TWgR0vR&index=11)***

After binge watching the discovery channel, you ditch your job as a trial lawyer to become a gold miner  . You decide to prospect five locations underneath a 7x7 grid of land. How much gold do you uncover at each location?
```
np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))

# print(gold)
# [[2 3 0 5 2 0 3]
#  [8 8 0 7 1 5 3]
#  [0 1 6 2 1 4 5]
#  [4 0 8 9 9 8 7]
#  [4 2 7 0 7 2 1]
#  [9 8 9 2 5 0 8]
#  [1 9 8 2 6 4 3]]

locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])
```

######***Solution***

In [ ]:
def main():
    np.random.seed(5555)
    gold = np.random.randint(low=0, high=10, size=(7,7))
    locs = np.array([[0,4],[2,2],[2,3],[5,1],[6,3]])
    for i, j in locs:
        print(f"Location : [{i},{j}], Gold Amount : {gold[i,j]}")

if __name__ == "__main__":
    main()

Location : [0,4], Gold Amount : 2
Location : [2,2], Gold Amount : 6
Location : [2,3], Gold Amount : 2
Location : [5,1], Gold Amount : 8
Location : [6,3], Gold Amount : 2


In [ ]:
def main():
    np.random.seed(5555)
    gold = np.random.randint(low=0, high=10, size=(7,7))
    locs = np.array([[0,4],[2,2],[2,3],[5,1],[6,3]])
    print(gold[locs[:,0],locs[:,1]])

if __name__ == "__main__":
    main()

[2 6 2 8 2]


####***Section 2 Slicing***

#####***Nola [blog](https://www.practiceprobs.com/problemsets/python-numpy/beginner/nola/)***

Make the following 4x7 array called nola that starts with 1 and steps by 2. However, note that the first element in each row is always 4 more than the last element in the previous row.

```
[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]
```

######***Solution***

In [ ]:
def main():
    x = np.arange(1,65,2).reshape((4,-1))[:,:-1]
    print(x)

if __name__ == "__main__":
    main()

[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]


###***Chapter 7 Filtering and Masking***

####***Section 2 Boolean Masking***

#####***Replace np.nan with -7000***

The numpy array `x` given below code contains `np.nan`. Replace those `np.nan` with -7000.
```
def main():
    x = np.array([
        [93., 84., 73., 68.],
        [97., 67., 57., np.nan],
        [87., 87., np.nan, 77.]
        ])
    print(x, end="\n\n")

if __name__ == "__main__":
    main()
```

######***Solution***

In [ ]:
def main():
    x = np.array([
        [93., 84., 73., 68.],
        [97., 67., 57., np.nan],
        [87., 87., np.nan, 77.]
        ])
    print(x, end="\n\n")
    
    bool_nan = np.isnan(x)
    print(bool_nan, end="\n\n")

    x[bool_nan] = -7000 # boolean masking
    print(x) 

if __name__ == "__main__":
    main()

[[93. 84. 73. 68.]
 [97. 67. 57. nan]
 [87. 87. nan 77.]]

[[False False False False]
 [False False False  True]
 [False False  True False]]

[[   93.    84.    73.    68.]
 [   97.    67.    57. -7000.]
 [   87.    87. -7000.    77.]]


###***Chapter 8 Component-Wise Operations***

####***Section 5 Broadcasting***

#####***Love Distance [eng](https://www.youtube.com/watch?v=SOXPwHDy1PA&list=PL9oKUrtC4VP6gDp1Vq3BzfViO0TWgR0vR&index=20)***

`u` is a vector of 2 components. Construct a $2\times2$ matrix `M` whose `i`, `j` component `M[i,j]` is `np.abs(u[i]-u[j])`.
```
def main():
    np.random.seed(1010)
    u = np.round( np.random.uniform(low=0, high=100, size=(10,)), 2 )
    print(u,end="\n\n")
    # [39.43 17.56  7.27 19.19 39.98 41.81 76.26 52.14 41.09 53.74]

if __name__ == "__main__":
    main()
```

######***Solution***

In [ ]:
def main():
    np.random.seed(1010)
    u = np.round( np.random.uniform(low=0, high=100, size=(10,)), 2 )
    print(u,end="\n\n")

    M = np.abs( u.reshape( (1,-1) ) - u.reshape( (-1,1) ) )
    print(M)

if __name__ == "__main__":
    main()

[39.43 17.56  7.27 19.19 39.98 41.81 76.26 52.14 41.09 53.74]

[[ 0.   21.87 32.16 20.24  0.55  2.38 36.83 12.71  1.66 14.31]
 [21.87  0.   10.29  1.63 22.42 24.25 58.7  34.58 23.53 36.18]
 [32.16 10.29  0.   11.92 32.71 34.54 68.99 44.87 33.82 46.47]
 [20.24  1.63 11.92  0.   20.79 22.62 57.07 32.95 21.9  34.55]
 [ 0.55 22.42 32.71 20.79  0.    1.83 36.28 12.16  1.11 13.76]
 [ 2.38 24.25 34.54 22.62  1.83  0.   34.45 10.33  0.72 11.93]
 [36.83 58.7  68.99 57.07 36.28 34.45  0.   24.12 35.17 22.52]
 [12.71 34.58 44.87 32.95 12.16 10.33 24.12  0.   11.05  1.6 ]
 [ 1.66 23.53 33.82 21.9   1.11  0.72 35.17 11.05  0.   12.65]
 [14.31 36.18 46.47 34.55 13.76 11.93 22.52  1.6  12.65  0.  ]]
